export const dsrList = [
  {
    id:1,
    s_no: 1,
    type: "text",
    isSortable: "sortable",
    action: [
      {
        icon: "",
        btnStyle: "btn_add_new",
        btnText: "pending",
        route: "DSR_DETAILS",
        type: "route",
        routeID: 121,
      },
    ],
    project_name: "	Trainee Project Angular",
    emp_name: "Shiva Saroj",
    email: "shiva.saroj@appinventiv.com",
    employment_type: "Permanent",
    date: "04-02-2023",
    status: "Submitted",
    pm_approval: "N/A",
    am_approval: "N/A",
    rm_approval: "N/A",
    logged_hr: "08:00",
    final_approve: "Pending",
    level_1: "	Suyash Saxena(AI057)",
    level_2: "HR (Human Resourse)",
    dsr: '<p style="box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px; border: 0px; font-family: Lato; font-size: 14px; background-color: #ffffff;">Meetings</p>\n<p style="box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px; border: 0px; font-family: Lato; font-size: 14px; background-color: #ffffff;">&nbsp; NA&nbsp;</p>\n<p style="box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px; border: 0px; font-family: Lato; font-size: 14px; background-color: #ffffff;">Task&nbsp;</p>\n<p style="box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px; border: 0px; font-family: Lato; font-size: 14px; background-color: #ffffff;">&nbsp; &nbsp;Bug fixing [2hr]</p>\n<p style="box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px; border: 0px; font-family: Lato; font-size: 14px; background-color: #ffffff;">&nbsp; &nbsp;Portal registration [1 hr]</p>\n<p style="box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px; border: 0px; font-family: Lato; font-size: 14px; background-color: #ffffff;">&nbsp; Working on job openings module [ 3 hr]</p>\n<p style="box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px; border: 0px; font-family: Lato; font-size: 14px; background-color: #ffffff;">Challenges</p>\n<p style="box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px; border: 0px; font-family: Lato; font-size: 14px; background-color: #ffffff;">NA</p>',
  },
  {
    id:2,
    s_no: 2,
    type: "text",
    isSortable: "sortable",
    action: [
      {
        icon: "",
        btnStyle: "btn_add_new",
        btnText: "pending",
        route: "DSR_DETAILS",
        type: "route",
        routeID: 121,
      },
    ],

    date: "04-06-2023",
    project_name: "	Trainee Project Angular",
    emp_name: "Shiva Saroj",
    email: "shiva.saroj@appinventiv.com",
    employment_type: "Permanent",
    status: "Submitted",
    pm_approval: "N/A",
    am_approval: "N/A",
    rm_approval: "N/A",
    logged_hr: "08:00",
    final_approve: "Pending",
    level_1: "	Suyash Saxena(AI057)",
    level_2: "HR (Human Resourse)",
    dsr: '<p style="box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px; border: 0px; font-family: Lato; font-size: 14px; background-color: #ffffff;">Meetings</p>\n<p style="box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px; border: 0px; font-family: Lato; font-size: 14px; background-color: #ffffff;">&nbsp; NA&nbsp;</p>\n<p style="box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px; border: 0px; font-family: Lato; font-size: 14px; background-color: #ffffff;">Task&nbsp;</p>\n<p style="box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px; border: 0px; font-family: Lato; font-size: 14px; background-color: #ffffff;">&nbsp; &nbsp;Bug fixing [2hr]</p>\n<p style="box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px; border: 0px; font-family: Lato; font-size: 14px; background-color: #ffffff;">&nbsp; &nbsp;Portal registration [1 hr]</p>\n<p style="box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px; border: 0px; font-family: Lato; font-size: 14px; background-color: #ffffff;">&nbsp; Working on job openings module [ 3 hr]</p>\n<p style="box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px; border: 0px; font-family: Lato; font-size: 14px; background-color: #ffffff;">Challenges</p>\n<p style="box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px; border: 0px; font-family: Lato; font-size: 14px; background-color: #ffffff;">NA</p>',
  },
  {
    id:3,

    s_no: 3,
    type: "text",
    isSortable: "sortable",
    action: [
      {
        icon: "",
        btnStyle: "btn_add_new",
        btnText: "pending",
        route: "DSR_DETAILS",
        type: "route",
        routeID: 121,
      },
    ],
    emp_name: "Shiva Saroj",
    email: "shiva.saroj@appinventiv.com",
    employment_type: "Permanent",
    date: "2023-05-25",
    project_name: "	Trainee Project Angular",
    status: "Submitted",
    pm_approval: "N/A",
    am_approval: "N/A",
    rm_approval: "N/A",
    logged_hr: "08:00",
    final_approve: "Pending",
    level_1: "	Suyash Saxena(AI057)",
    level_2: "HR (Human Resourse)",
    dsr: '<p style="box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px; border: 0px; font-family: Lato; font-size: 14px; background-color: #ffffff;">Meetings</p>\n<p style="box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px; border: 0px; font-family: Lato; font-size: 14px; background-color: #ffffff;">&nbsp; NA&nbsp;</p>\n<p style="box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px; border: 0px; font-family: Lato; font-size: 14px; background-color: #ffffff;">Task&nbsp;</p>\n<p style="box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px; border: 0px; font-family: Lato; font-size: 14px; background-color: #ffffff;">&nbsp; &nbsp;Bug fixing [2hr]</p>\n<p style="box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px; border: 0px; font-family: Lato; font-size: 14px; background-color: #ffffff;">&nbsp; &nbsp;Portal registration [1 hr]</p>\n<p style="box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px; border: 0px; font-family: Lato; font-size: 14px; background-color: #ffffff;">&nbsp; Working on job openings module [ 3 hr]</p>\n<p style="box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px; border: 0px; font-family: Lato; font-size: 14px; background-color: #ffffff;">Challenges</p>\n<p style="box-sizing: border-box; margin: 0px 0px 1rem; padding: 0px; border: 0px; font-family: Lato; font-size: 14px; background-color: #ffffff;">NA</p>',
  },
];
